apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipa-frontend
  namespace: ipa-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipa-frontend
  template:
    metadata:
      labels:
        app: ipa-frontend
    spec:
      containers:
      - name: frontend
        image: "ayyaya21/mahagarp-frontend:latest" 
        ports:
        - containerPort: 80 
---

apiVersion: v1
kind: Service
metadata:
  name: ipa-frontend-svc
  namespace: ipa-project
spec:
  selector:
    app: ipa-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80