apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ipa-project-ingress
  namespace: ipa-project
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "ipa.local"
  rules:
  - host: "ipa.local"
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ipa-backend-svc
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ipa-frontend-svc
            port:
              number: 80